export const GLOBAL_ERROR_SET = 'GLOBAL_ERROR_SET'
export const GLOBAL_ERROR_CLEAR = 'GLOBAL_ERROR_CLEAR'

export const GET_CURRENT_CITY = 'GET_CURRENT_CITY'
export const GET_CURRENT_CITY_SUCCESS = 'GET_CURRENT_CITY_SUCCESS'
export const GET_CURRENT_CITY_FAILUE = 'GET_CURRENT_CITY_FAILUE'

export const SET_SELECTED_CITY = 'SET_SELECTED_CITY'
export const SET_SELECTED_DATA_FORECAST = 'SET_SELECTED_DATA_FORECAST'

export const GET_CURRENT_WEATHER_STATUS = 'GET_CURRENT_WEATHER_STATUS'
export const GET_CURRENT_WEATHER_STATUS_SUCCESS = 'GET_CURRENT_WEATHER_STATUS_SUCCESS'
export const GET_CURRENT_WEATHER_STATUS_FAILURE = 'GET_CURRENT_WEATHER_STATUS_FAILURE'

export const GET_FUTURE_WEATHER_STATUS = 'GET_FUTURE_WEATHER_STATUS'
export const GET_FUTURE_WEATHER_STATUS_SUCCESS = 'GET_FUTURE_WEATHER_STATUS_SUCCESS'
export const GET_FUTURE_WEATHER_STATUS_FAILURE = 'GET_FUTURE_WEATHER_STATUS_FAILURE'


